# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.6

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install

after_success:
    - bash <(curl -s https://codecov.io/bash)

# Commands you want to run that will verify your build.
script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always